### PR TITLE
Actions are data, not state

### PR DESCRIPTION
**Pull request by Gurkenglas**
Inspect before merging, I may have spaghetti'd this one. Also maybe you want to squash the commits into one to not litter the history with the PRs I'm doing in the other direction to catch up on your commits. Am I doing this wrong?

### CODE REVIEW

**Comment by DAHeath** [comment]
Yeah sorry about the filthy history, I'll start using separate branches and then making coherent commits. It make take me a bit longer to go over this change, like you said.

A good sanity check is to try out some of the traversals. So if you build a graph with a path and numeric vertices, you could do something like:

`path 'a' 'b' (\e -> print e >> return e) (\v -> print v >> return (v + 5)) myGraph`

And then make sure that the vertices and edges on the path are printed in the correct order, and that only the vertices in the path between the indices are modified.

**Comment by Gurkenglas** [comment]
Oh, I don't really more than usual expect it to be wrong, I just thought you might think the readability has suffered.

**Comment by DAHeath** [comment]
Got it. Well I felt all my implementations of these traversals were pretty ugly to begin with, so I'm sure I'll end up agreeing with your changes.

**Comment by DAHeath** [comment]
It looks like the changes you made don't quite work correctly. When I just run the test suite I've written so far, dfs fails and bfs goes into an infinite loop.

**Comment by Gurkenglas** [comment]
Ugh, boolean blindness - `unless` translates into `guard (not b)`. Fixed. I suppose I learned something about testing. `stack test --profile --coverage` made a `.tix` file with which `stack hpc report ord-graph-test.tix` made a .html file that shows it never getting through lines 544/556. (Haven't yet figured out how to get useful information from the .prof file.) Tests go through now for me.

**Pull request merged**
